---
- name: config_php | Installing PHP-{{ nginx_php_ver }}
  community.general.packaging.os.apk:
    name:
      [
        "{{ 'php' + nginx_php_ver }}",
        "{{ 'php' + nginx_php_ver + '-cli' }}",
        "{{ 'php' + nginx_php_ver + '-fpm' }}",
      ]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    ansible_os_family == "Alpine"

- name: config_php | Installing PHP-{{ nginx_php_ver }}
  ansible.builtin.apt:
    name:
      [
        "{{ 'php' + nginx_php_ver }}",
        "{{ 'php' + nginx_php_ver + '-cli' }}",
        "{{ 'php' + nginx_php_ver + '-fpm' }}",
      ]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    ansible_os_family == "Debian"

- name: config_php | Configuring php.ini
  ansible.builtin.template:
    src: "{{ nginx_php_path + '/' + item + '.j2' }}"
    dest: "{{ '/' + nginx_php_path + '/' + item }}"
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart nginx
    - "restart php{{ nginx_php_ver }}-fpm"
  with_items:
    - fpm/php.ini
    - cli/php.ini
  when: >
    ansible_os_family == "Debian"
