---
- name: redhat | Installing EPEL repo (RedHat)
  ansible.builtin.yum:
    name: epel-release
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing NGINX
  ansible.builtin.dnf:
    name: nginx
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Installing NGINX
  ansible.builtin.yum:
    name: nginx
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Ensuring NGINX is started and enabled on boot
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  become: true
