---
- name: setting Alpine facts
  set_fact:
    nginx_web_group: nginx
    nginx_web_owner: nginx
    nginx_web_root: /var/lib/nginx/html
  when: ansible_os_family == "Alpine"

- name: setting Debian facts
  set_fact:
    nginx_web_group: www-data
    nginx_web_owner: www-data
    nginx_web_root: /usr/share/nginx/html
  when: ansible_os_family == "Debian"

- name: setting RedHat facts
  set_fact:
    nginx_web_group: nginx
    nginx_web_owner: nginx
    nginx_web_root: /usr/share/nginx/html
  when: ansible_os_family == "RedHat"

- name: setting PHP version
  set_fact:
    nginx_php_fpm_socket: /var/run
    # no leading / for template path
    nginx_php_path: etc/php5
    nginx_php_ver: "5"
  when: >
    (ansible_distribution == "Debian" and
    ansible_distribution_major_version|int < 9) or
    (ansible_distribution == "Ubuntu" and
    ansible_distribution_version <= '14.04')

- name: setting PHP version
  set_fact:
    nginx_php_fpm_socket: /var/run/php
    # no leading / for template path
    nginx_php_path: etc/php/5
    nginx_php_ver: "5"
  when: >
    ansible_os_family == "Alpine" and
    ansible_distribution_major_version|int < 3

- name: setting PHP version
  set_fact:
    nginx_php_fpm_socket: /var/run/php
    # no leading / for template path
    nginx_php_path: etc/php/7
    nginx_php_ver: "7"
  when: >
    ansible_os_family == "Alpine" and
    ansible_distribution_major_version|int >= 3

- name: setting PHP version
  set_fact:
    nginx_php_fpm_socket: /var/run/php
    # no leading / for template path
    nginx_php_path: etc/php/7.0
    nginx_php_ver: "7.0"
  when: >
    (ansible_distribution == "Debian" and
    ansible_distribution_major_version|int == 9) or
    (ansible_distribution == "Ubuntu" and
    ansible_distribution_version == '16.04')

- name: setting PHP version
  set_fact:
    nginx_php_fpm_socket: /var/run/php
    # no leading / for template path
    nginx_php_path: etc/php/7.2
    nginx_php_ver: "7.2"
  when: >
    (ansible_distribution == "Debian" and
    ansible_distribution_major_version|int == 10) or
    (ansible_distribution == "Ubuntu" and
    ansible_distribution_version >= '18.04')

- name: setting PHP version
  set_fact:
    nginx_php_fpm_socket: /var/run/php
    # no leading / for template path
    nginx_php_path: etc/php/7.3
    nginx_php_ver: "7.3"
  when: >
    (ansible_distribution == "Debian" and
    ansible_distribution_major_version|int == 10)

- name: setting PHP version
  set_fact:
    nginx_php_fpm_socket: /var/run/php
    # no leading / for template path
    nginx_php_path: etc/php/7.4
    nginx_php_ver: "7.4"
  when: >
    (ansible_distribution == "Debian" and
    ansible_distribution_major_version|int == 11)

