---
# handlers file for ansible-nginx
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: restart php5-fpm
  ansible.builtin.service:
    name: php5-fpm
    state: restarted
  become: true

- name: restart php7.0-fpm
  ansible.builtin.service:
    name: php7.0-fpm
    state: restarted
  become: true

- name: restart php7.2-fpm
  ansible.builtin.service:
    name: php7.2-fpm
    state: restarted
  become: true

- name: restart php7.3-fpm
  ansible.builtin.service:
    name: php7.3-fpm
    state: restarted
  become: true

- name: restart php7.4-fpm
  ansible.builtin.service:
    name: php7.4-fpm
    state: restarted
  become: true
